# Generated by Django 6.0.7 on 2026-08-05 13:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("site_settings", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SiteSpecificSettings",
        ),
    ]
