# Generated by Django 5.2.8 on 2026-01-23 17:09

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("wagtailcore", "0095_groupsitepermission"),
    ]

    operations = [
        migrations.CreateModel(
            name="TimelinePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [
                            ("timeline", 4),
                            ("heading_block", 7),
                            ("paragraph_block", 8),
                            ("image_block", 11),
                        ],
                        blank=True,
                        block_lookup={
                            0: ("wagtail.blocks.CharBlock", (), {}),
                            1: ("wagtail.blocks.RichTextBlock", (), {"blank": True}),
                            2: ("wagtail.blocks.DateBlock", (), {}),
                            3: (
                                "wagtail.blocks.StructBlock",
                                [[("title", 0), ("description", 1), ("date", 2)]],
                                {"blank": True, "required": False},
                            ),
                            4: (
                                "wagtail.blocks.StreamBlock",
                                [[("events", 3)]],
                                {"blank": True, "required": False},
                            ),
                            5: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"form_classname": "title", "required": True},
                            ),
                            6: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "blank": True,
                                    "choices": [
                                        ("", "Select a heading size"),
                                        ("h2", "H2"),
                                        ("h3", "H3"),
                                        ("h4", "H4"),
                                    ],
                                    "required": False,
                                },
                            ),
                            7: (
                                "wagtail.blocks.StructBlock",
                                [[("heading_text", 5), ("size", 6)]],
                                {},
                            ),
                            8: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {"icon": "pilcrow"},
                            ),
                            9: ("wagtail.images.blocks.ImageBlock", [], {}),
                            10: ("wagtail.blocks.CharBlock", (), {"required": False}),
                            11: (
                                "wagtail.blocks.StructBlock",
                                [[("image", 9), ("caption", 10), ("attribution", 10)]],
                                {},
                            ),
                        },
                        help_text="body",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
