name: uk-retejo

secrets:
  POSTGRES_PASSWORD:
    file: ./containers/secrets/POSTGRES_PASSWORD

services:

  caddy:
    image: caddy:alpine
    user: $USER_ID:$GROUP_ID
    environment:
      - LOCAL_HOST=${LOCAL_HOST}
    ports:
      - 127.0.0.1:443:443
      - 127.0.0.1:24678:24678
    volumes:
      - ./containers/volumes/caddy/data:/data:Z
      - ./containers/volumes/caddy/etc/caddy:/etc/caddy:Z
    networks:
      - public
      - backend

  django:
    build:
      dockerfile: containers/Containerfile
      target: development
      args:
      - HOME=/backend
      - USER_ID=$USER_ID
      - GROUP_ID=$GROUP_ID
    command: /bin/sh -c "./manage.py migrate && ./manage.py ${DJANGO_RUNSERVER:-serve}"
    user: $USER_ID:$GROUP_ID
    secrets:
      - POSTGRES_PASSWORD
    env_file:
      - backend/.env
    environment:
      - DJANGO_ALLOW_ASYNC_UNSAFE=1
      - GRANIAN_RUNTIME_MODE=s
    volumes:
      - ./backend:/backend:z
      - ./containers/volumes/assets:/assets:z
    working_dir: /backend
    depends_on:
      - caddy
      - postgres
    restart: unless-stopped
    stop_grace_period: 2s
    hostname: django
    networks:
      - public
      - backend
    develop:
      watch:
        - action: rebuild
          path: backend/uv.lock

  postgres:
    image: postgres:18-alpine
    user: $USER_ID:$GROUP_ID
    secrets:
      - POSTGRES_PASSWORD
    volumes:
      - ./containers/volumes/postgresql:/var/lib/postgresql:Z
      - ./containers/volumes/postgresql/uk-retejo-dump.sql.gz:/docker-entrypoint-initdb.d/dump.sql.gz:Z
    environment:
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD_FILE=/run/secrets/POSTGRES_PASSWORD
    restart: unless-stopped
    networks:
      - backend

  tailwind:
    image: node:24-alpine
    volumes:
      - ./backend:/backend:z
      - ./style:/style:z
    working_dir: /style
    # tty: true
    user: $USER_ID:$GROUP_ID
    command: /bin/sh -c "npm i; npm run watch:css"

  vue:
    image: node:24-alpine
    user: $USER_ID:$GROUP_ID
    volumes:
      - ./backend:/backend:z
      - ./uk-aligxilo:/uk-aligxilo:z
    working_dir: /uk-aligxilo
    command: /bin/sh -c "npm i && npm run dev"
    tty: true
    networks:
      - backend

networks:
  public:
  backend:
