# Generated by Django 6.0.7 on 2026-08-05 09:45

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("program", "0004_programproposalpage_header_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="programproposalpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("program_type", 6),
                    ("heading_block", 9),
                    ("paragraph_block", 10),
                    ("image_block", 13),
                ],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"label": "Title (day)"}),
                    1: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0)]],
                        {"blank": True, "required": False},
                    ),
                    2: ("wagtail.blocks.CharBlock", (), {}),
                    3: (
                        "wagtail.blocks.DateBlock",
                        (),
                        {"blank": True, "required": False},
                    ),
                    4: ("wagtail.blocks.RichTextBlock", (), {"blank": True}),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 2), ("deadline", 3), ("description", 4)]],
                        {"blank": True, "required": False},
                    ),
                    6: (
                        "wagtail.blocks.StreamBlock",
                        [[("title_day", 1), ("program_type", 5)]],
                        {"blank": True, "required": False},
                    ),
                    7: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"form_classname": "title", "required": True},
                    ),
                    8: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "blank": True,
                            "choices": [
                                ("", "Select a heading size"),
                                ("h2", "H2"),
                                ("h3", "H3"),
                                ("h4", "H4"),
                            ],
                            "required": False,
                        },
                    ),
                    9: (
                        "wagtail.blocks.StructBlock",
                        [[("heading_text", 7), ("size", 8)]],
                        {},
                    ),
                    10: ("wagtail.blocks.RichTextBlock", (), {"icon": "pilcrow"}),
                    11: ("wagtail.images.blocks.ImageBlock", [], {}),
                    12: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    13: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 11), ("caption", 12), ("attribution", 12)]],
                        {},
                    ),
                },
            ),
        ),
    ]
