# Generated by Django 6.0.8 on 2026-10-02 15:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("program", "0005_alter_programproposalpage_body"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="timelinepage",
            name="header_image",
        ),
        migrations.RemoveField(
            model_name="timelinepage",
            name="page_ptr",
        ),
        migrations.DeleteModel(
            name="ProgramProposalPage",
        ),
        migrations.DeleteModel(
            name="TimelinePage",
        ),
    ]
