# Generated by Django 6.0.2 on 2026-03-10 09:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("registration", "0002_vuepage_alter_registrationpage_vue_module"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="registrationpage",
            name="vue_module",
        ),
    ]
