# Generated by Django 6.0.8 on 2026-09-24 14:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "registration",
            "0004_registrationpage_header_image_vuepage_header_image_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="vuepage",
            name="vue_module",
            field=models.CharField(
                choices=[
                    ("registration", "Aliĝilo"),
                    ("edit", "Mendilo"),
                    ("participants", "Aliĝintoj"),
                    ("price", "Kotizoj"),
                ],
                default="participants",
            ),
        ),
    ]
