# Generated by Django 6.0.8 on 2026-09-24 15:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("registration", "0005_alter_vuepage_vue_module"),
    ]

    operations = [
        migrations.DeleteModel(
            name="RegistrationPage",
        ),
    ]
