# Generated by Django 6.0.8 on 2026-09-28 09:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registration", "0006_delete_registrationpage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vuepage",
            name="vue_module",
            field=models.CharField(
                choices=[
                    ("registration", "Aliĝilo"),
                    ("edit", "Mendilo"),
                    ("participants", "Aliĝintoj"),
                    ("price", "Kotizoj"),
                ],
                default="registration",
            ),
        ),
    ]
