# Generated by Django 6.0.8 on 2026-10-02 15:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("registration", "0007_alter_vuepage_vue_module"),
    ]

    operations = [
        migrations.DeleteModel(
            name="VuePage",
        ),
    ]
