# Generated by Django 5.2.8 on 2025-11-22 18:15

from django.db import migrations, models

DEFAULT_ICONS = [
    {"css_class": "fa-solid fa-water", "name": "Akvo"},
    {"css_class": "fa-regular fa-lightbulb", "name": "Ampolo"},
    {"css_class": "fa-solid fa-plug-circle-bolt", "name": "Electro"},
    {"css_class": "fa-solid fa-users", "name": "Grupo"},
    {"css_class": "fa-regular fa-clock", "name": "Horloĝo"},
    {"css_class": "fa-regular fa-comments", "name": "Komentoj"},
    {"css_class": "fa-regular fa-square", "name": "Kvadrato"},
    {"css_class": "fa-solid fa-coins", "name": "Moneroj"},
    {"css_class": "fa-regular fa-comment", "name": "Parolo"},
    {"css_class": "fa-regular fa-star", "name": "Star"},
    {"css_class": "fa-solid fa-masks-theater", "name": "Teatraj maskoj"},
    {"css_class": "fa-solid fa-phone", "name": "Telephono"},
    {"css_class": "fa-solid fa-earth-africa", "name": "Tero"},
    {"css_class": "fa-solid fa-users", "name": "Uzantoj"},
    {"css_class": "fa-solid fa-cloud-sun", "name": "Vetero"},
]


def initial_icons(apps, schema_editor):
    FontAwesomeIcon = apps.get_model("base", "FontAwesomeIcon")
    for icon in DEFAULT_ICONS:
        FontAwesomeIcon.objects.create(**icon)


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FontAwesomeIcon",
            options={
                "ordering": ["name"],
                "verbose_name": "FontAwesome ikono",
                "verbose_name_plural": "FontAwesome ikonoj",
            },
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Uzantoj, Tero,…", max_length=20, verbose_name="name"
                    ),
                ),
                (
                    "css_class",
                    models.CharField(
                        help_text="'fa-regular fa-users'",
                        max_length=50,
                        verbose_name="CSS class",
                    ),
                ),
            ],
        ),
        migrations.RunPython(initial_icons, migrations.RunPython.noop),
    ]
