# --- BASE STAGE ---
FROM python:3.14-alpine AS base

ARG HOME=/backend
ENV VIRTUAL_ENV=/opt/venv
ENV HOME=$HOME \
    PATH="$VIRTUAL_ENV/bin:$PATH" \
    PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1 \
    UV_PROJECT_ENVIRONMENT=$VIRTUAL_ENV

RUN apk add --no-cache just


# --- BUILDER STAGE ---
FROM ghcr.io/astral-sh/uv:python3.14-alpine AS builder

ARG HOME

ENV UV_COMPILE_BYTECODE=1 \
    UV_LINK_MODE=copy \
    UV_PROJECT_ENVIRONMENT=/opt/venv

WORKDIR $HOME

# Install the project's dependencies using the lockfile and settings
RUN --mount=type=cache,target=/root/.cache/uv \
    --mount=type=bind,source=backend/uv.lock,target=uv.lock \
    --mount=type=bind,source=backend/pyproject.toml,target=pyproject.toml \
    uv sync --frozen --no-install-project --no-dev



# --- DEVELOPMENT STAGE ---
FROM base AS development

COPY --from=builder --chown=dj:dj $VIRTUAL_ENV $VIRTUAL_ENV
 
RUN \
--mount=from=ghcr.io/astral-sh/uv,source=/uv,target=/bin/uv \
--mount=type=cache,target=/root/.cache/uv \
--mount=type=bind,source=backend/uv.lock,target=uv.lock \
--mount=type=bind,source=backend/pyproject.toml,target=pyproject.toml \
UV_SYSTEM_PYTHON=1 uv sync --frozen

RUN source $VIRTUAL_ENV/bin/activate

WORKDIR $HOME

# USER $USER



# --- VITE STAGE ---
FROM node:24-alpine AS vite-build

RUN \
--mount=type=cache,target=/root/.npm,rw \
--mount=type=bind,source=uk-aligxilo/package.json,target=package.json \
--mount=type=bind,source=uk-aligxilo/package-lock.json,target=package-lock.json \
npm ci

COPY uk-aligxilo/ /uk-aligxilo/
WORKDIR /uk-aligxilo
RUN npm run build



# --- PRODUCTION STAGE ---
FROM base AS production

ARG USER_ID=1030  # On ikso.net: compose
ARG GROUP_ID=33  # On ikso.net: www-data
ARG GIT_BRANCH=no-branch
ARG COMMIT_HASH=no-hash
ARG VITE_OUT_DIR

ENV USER=dj \
    USER_ID=$USER_ID \
    GROUP_ID=$GROUP_ID \
    UV_CACHE_DIR=/root/.cache/uv \
    UV_LINK_MODE=copy \
    UK_GIT_BRANCH=$GIT_BRANCH \
    UK_COMMIT_HASH=$COMMIT_HASH

RUN \
addgroup -g $GROUP_ID $USER && \
adduser -D -h $HOME -u $USER_ID -G $USER $USER && \
install --directory -o $USER -g $USER -m 0755 /assets

COPY --from=builder --chown=$USER_ID:$GROUP_ID $VIRTUAL_ENV $VIRTUAL_ENV

# Add the rest of the project source code and install it
# Installing separately from its dependencies allows optimal layer caching
COPY --chown=$USER:$GROUP_ID backend $HOME/

WORKDIR $HOME

RUN \
--mount=from=ghcr.io/astral-sh/uv,source=/uv,target=/bin/uv \
--mount=type=cache,target=$UV_CACHE_DIR \
uv sync --frozen --no-dev

# Install Vite/Vue project
COPY --from=vite-build --chown=$USER:$GROUP_ID /$VITE_OUT_DIR ./$VITE_OUT_DIR

COPY --from=vite-build --chmod=+x ./uk-aligxilo/replace-vite-env.sh /bin/

USER $USER

RUN UK_RETEJO_ENVIRONMENT="build" python manage.py collectstatic -v 2 --noinput

EXPOSE 8000
