# Generated by Django 6.0.3 on 2026-04-13 13:39

import django.db.models.deletion
import evente.choices
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("wagtailcore", "0096_referenceindex_referenceindex_source_object_and_more"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="SimplePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "sections",
                    wagtail.fields.StreamField(
                        [("section", 12)],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "default": "",
                                    "label": "CSS class",
                                    "required": False,
                                },
                            ),
                            1: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "default": "",
                                    "label": "CSS style",
                                    "required": False,
                                },
                            ),
                            2: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "choices": [("mt-[-95px]", "-95px")],
                                    "default": "",
                                    "label": "Margin top",
                                    "required": False,
                                },
                            ),
                            3: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "choices": [],
                                    "default": "",
                                    "label": "Margin bottom",
                                    "required": False,
                                },
                            ),
                            4: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "choices": [
                                        ("pt-[80px]", "80px"),
                                        ("pt-[110px] max-2xl:!pt-[70px]", "110px"),
                                        ("pt-[130px] max-2xl:!pt-[90px]", "130px"),
                                        ("pt-[140px] max-2xl:!pt-[100px]", "140px"),
                                        ("pt-[155px] max-2xl:!pt-[100px]", "155px"),
                                        ("pt-[200px]", "200px"),
                                    ],
                                    "default": "pt-[140px] max-2xl:!pt-[100px]",
                                    "label": "Padding top",
                                    "required": False,
                                },
                            ),
                            5: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "choices": [
                                        ("pb-[80px]", "80px"),
                                        ("pb-[110px] max-2xl:!pb-[70px]", "110px"),
                                        ("pb-[130px] max-2xl:!pb-[90px]", "130px"),
                                        ("pb-[140px] max-2xl:!pb-[100px]", "140px"),
                                        ("pb-[155px] max-2xl:!pb-[100px]", "155px"),
                                        ("pb-[200px]", "200px"),
                                    ],
                                    "default": "pb-[110px] max-2xl:!pb-[70px]",
                                    "label": "Padding bottom",
                                    "required": False,
                                },
                            ),
                            6: (
                                "wagtail.images.blocks.ImageChooserBlock",
                                (),
                                {"label": "Background image", "required": False},
                            ),
                            7: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "choices": evente.choices.TailwindColors,
                                    "label": "Background color",
                                    "required": False,
                                },
                            ),
                            8: (
                                "wagtail.blocks.IntegerBlock",
                                (),
                                {
                                    "choices": evente.choices.TailwindLightness,
                                    "label": "Background color lightness",
                                    "null": True,
                                    "required": False,
                                },
                            ),
                            9: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "choices": evente.choices.TailwindBackgroundPosition,
                                    "default": "bg-center",
                                    "label": "Background position",
                                    "required": False,
                                },
                            ),
                            10: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "choices": evente.choices.TailwindBackgroundRepeat,
                                    "default": "bg-no-repeat",
                                    "label": "Background repeat",
                                    "required": False,
                                },
                            ),
                            11: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "choices": evente.choices.TailwindBackgroundSize,
                                    "default": "bg-cover",
                                    "label": "Background size",
                                    "required": False,
                                },
                            ),
                            12: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("css_class", 0),
                                        ("css_style", 1),
                                        ("margin_top", 2),
                                        ("margin_bottom", 3),
                                        ("padding_top", 4),
                                        ("padding_bottom", 5),
                                        ("bg_image", 6),
                                        ("bg_color", 7),
                                        ("bg_lightness", 8),
                                        ("bg_position", 9),
                                        ("bg_repeat", 10),
                                        ("bg_size", 11),
                                    ]
                                ],
                                {},
                            ),
                        },
                    ),
                ),
                (
                    "header_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
