# Generated by Django 6.0.3 on 2026-04-13 14:44

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="simplepage",
            name="sections",
        ),
        migrations.AddField(
            model_name="simplepage",
            name="body",
            field=wagtail.fields.StreamField(
                [("section", 17)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Subtitle", "required": False},
                    ),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Title", "required": False},
                    ),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Text", "required": False},
                    ),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("subtitle", 0), ("title", 1), ("text", 2)]],
                        {},
                    ),
                    4: (
                        "wagtail.blocks.StreamBlock",
                        [[("title", 3)]],
                        {"required": False},
                    ),
                    5: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "", "label": "CSS class", "required": False},
                    ),
                    6: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "", "label": "CSS style", "required": False},
                    ),
                    7: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("mt-[-95px]", "-95px")],
                            "label": "Margin top",
                            "required": False,
                        },
                    ),
                    8: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [], "label": "Margin bottom", "required": False},
                    ),
                    9: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("pt-[80px]", "80px"),
                                ("pt-[110px] max-2xl:!pt-[70px]", "110px"),
                                ("pt-[130px] max-2xl:!pt-[90px]", "130px"),
                                ("pt-[140px] max-2xl:!pt-[100px]", "140px"),
                                ("pt-[155px] max-2xl:!pt-[100px]", "155px"),
                                ("pt-[200px]", "200px"),
                            ],
                            "label": "Padding top",
                            "required": False,
                        },
                    ),
                    10: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("pb-[80px]", "80px"),
                                ("pb-[110px] max-2xl:!pb-[70px]", "110px"),
                                ("pb-[130px] max-2xl:!pb-[90px]", "130px"),
                                ("pb-[140px] max-2xl:!pb-[100px]", "140px"),
                                ("pb-[155px] max-2xl:!pb-[100px]", "155px"),
                                ("pb-[200px]", "200px"),
                            ],
                            "label": "Padding bottom",
                            "required": False,
                        },
                    ),
                    11: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"label": "Background image", "required": False},
                    ),
                    12: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("red", "Red"),
                                ("orange", "Orange"),
                                ("amber", "Amber"),
                                ("yellow", "Yellow"),
                                ("lime", "Lime"),
                                ("green", "Green"),
                                ("emerald", "Emerald"),
                                ("teal", "Teal"),
                                ("cyan", "Cyan"),
                                ("sky", "Sky"),
                                ("blue", "Blue"),
                                ("indigo", "Indigo"),
                                ("violet", "Violet"),
                                ("purple", "Purple"),
                                ("fuchsia", "Fuchsia"),
                                ("pink", "Pink"),
                                ("rose", "Rose"),
                                ("slate", "Slate"),
                                ("gray", "Gray"),
                                ("zinc", "Zinc"),
                                ("neutral", "Neutral"),
                                ("stone", "Stone"),
                                ("taupe", "Taupe"),
                                ("mauve", "Mauve"),
                                ("mist", "Mist"),
                                ("olive", "Olive"),
                            ],
                            "label": "Background color",
                            "required": False,
                        },
                    ),
                    13: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                (50, "50"),
                                (100, "100"),
                                (200, "200"),
                                (300, "300"),
                                (400, "400"),
                                (500, "500"),
                                (600, "600"),
                                (700, "700"),
                                (800, "800"),
                                (900, "900"),
                                (950, "950"),
                            ],
                            "label": "Background color lightness",
                            "required": False,
                        },
                    ),
                    14: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("bg-top-left", "Top left"),
                                ("bg-top", "Top"),
                                ("bg-top-right", "Top right"),
                                ("bg-left", "Left"),
                                ("bg-center", "Center"),
                                ("bg-right", "Right"),
                                ("bg-bottom-left", "Bottom left"),
                                ("bg-bottom", "Bottom"),
                                ("bg-bottom-right", "Bottom right"),
                            ],
                            "label": "Background position",
                            "required": False,
                        },
                    ),
                    15: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("bg-repeat", "Repeat"),
                                ("bg-repeat-x", "X"),
                                ("bg-repeat-y", "Y"),
                                ("bg-repeat-space", "Space"),
                                ("bg-repeat-round", "Round"),
                                ("bg-no-repeat", "No repeat"),
                            ],
                            "label": "Background repeat",
                            "required": False,
                        },
                    ),
                    16: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("bg-auto", "Auto"),
                                ("bg-cover", "Cover"),
                                ("bg-contain", "Contain"),
                            ],
                            "label": "Background size",
                            "required": False,
                        },
                    ),
                    17: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("content", 4),
                                ("css_class", 5),
                                ("css_style", 6),
                                ("margin_top", 7),
                                ("margin_bottom", 8),
                                ("padding_top", 9),
                                ("padding_bottom", 10),
                                ("bg_image", 11),
                                ("bg_color", 12),
                                ("bg_lightness", 13),
                                ("bg_position", 14),
                                ("bg_repeat", 15),
                                ("bg_size", 16),
                            ]
                        ],
                        {},
                    ),
                },
                verbose_name="body",
            ),
        ),
    ]
