__all__ = [
    "AGE_GROUPS",
    "AGE_GROUP_WEIGHTS",
    "COUNTRIES",
    "COUNTRY_WEIGHTS",
    "MISSING_FIELDS",
    "LOCALES_BY_COUNTRY",
]

AGE_GROUPS = ["child", "youth", "membershipyouth", "adult", None]
AGE_GROUP_WEIGHTS = [5, 15, 15, 60, 5]

COUNTRIES = (
    "AL AM AO AR AT AU BE BG BI BJ BO BR BY CA CD CH CN CU CZ DE DK "
    "EE ES FI FR GA GB GH GR HK HR HU IE IL IR IS IT JP KR LT LU LV "
    "MG MN MX NL NO NP NZ PK PL RO RS RU SE SI SK TG TR TW TZ UA US"
).split()
COUNTRY_WEIGHTS = [
    1, 3, 4, 2, 18, 3, 25, 5, 7, 2, 1, 33, 2, 19, 10, 23, 43, 8, 133, 123,
    14, 5, 30, 13, 98, 1, 20, 1, 1, 1, 12, 47, 2, 3, 1, 1, 29, 27, 36, 18, 8,
    11, 4, 3, 8, 27, 6, 8, 1, 3, 111, 11, 3, 5, 14, 8, 29, 2, 1, 1, 4, 5, 31
]  # fmt: skip

MISSING_FIELDS = [
    "lando",
    "persona_nomo",
    "familia_nomo",
    "genro",
    "titolo",
    "naskigxdato",
    "retadreso",
    "adreso",
    "urbo",
    "posxtkodo",
    "telefono",
]

# Taken from https://github.com/joke2k/faker/tree/master/faker/providers/person
LOCALES_BY_COUNTRY = {
    "AA": ["ar_AA"],
    "AM": ["hy_AM"],
    "AR": ["es_AR"],
    "AT": ["de_AT"],
    "AZ": ["az_AZ"],
    "BD": ["bn_BD"],
    "BE": ["fr_BE", "nl_BE"],
    "BG": ["bg_BG"],
    "BR": ["pt_BR"],
    "CA": ["es_CA", "fr_CA"],
    "CH": ["de_CH", "fr_CH"],
    "CL": ["es_CL"],
    "CN": ["zh_CN"],
    "CO": ["es_CO"],
    "CZ": ["cs_CZ"],
    "DE": ["de_DE"],
    "DK": ["da_DK"],
    "DZ": ["ar_DZ", "fr_DZ"],
    "EE": ["et_EE"],
    "ES": ["es_ES"],
    "FI": ["fi_FI"],
    "FR": ["fr_FR"],
    "GB": ["en_GB"],
    "GE": ["ka_GE"],
    "GH": ["tw_GH"],
    "GR": ["el_GR"],
    "HR": ["hr_HR"],
    "HU": ["hu_HU"],
    "ID": ["id_ID"],
    "IE": ["en_IE", "ga_IE"],
    "IL": ["he_IL"],
    "IN": ["en_IN", "gu_IN", "hi_IN", "or_IN", "ta_IN"],
    "IR": ["fa_IR"],
    "IS": ["is_IS"],
    "IT": ["it_IT"],
    "JP": ["ja_JP"],
    "KE": ["en_KE"],
    "KR": ["ko_KR"],
    "LI": ["de_LI"],
    "LT": ["lt_LT"],
    "LU": ["de_LU"],
    "LV": ["lv_LV"],
    "MX": ["es_MX"],
    "NG": ["en_NG", "ha_NG", "ig_NG", "yo_NG"],
    "NL": ["nl_NL"],
    "NO": ["no_NO"],
    "NP": ["ne_NP"],
    "NZ": ["en_NZ"],
    "PK": ["en_PK"],
    "PL": ["pl_PL"],
    "PS": ["ar_PS"],
    "PT": ["pt_PT"],
    # "QC": ["fr_QC"],  # Deprecated
    "RO": ["ro_RO"],
    "RU": ["ru_RU"],
    "SA": ["ar_SA"],
    "SE": ["sv_SE"],
    "SI": ["sl_SI"],
    "SK": ["sk_SK"],
    "TH": ["en_TH", "th_TH"],
    "TR": ["tr_TR"],
    "TW": ["zh_TW"],
    "UA": ["uk_UA"],
    "US": ["en_US"],
    "UZ": ["uz_UZ"],
    "VN": ["vi_VN"],
    "ZA": ["zu_ZA"],
    # Overrides from UK partoprenantoj:
    "AL": ["el_GR"],
    "AO": ["pt_BR"],
    "AU": ["en_GB"],
    "BI": ["fr_BE", "ha_NG", "ig_NG", "yo_NG"],
    "BJ": ["fr_BE", "ha_NG", "ig_NG", "yo_NG"],
    "BO": ["es_AR", "es_CL", "es_CO", "es_MX"],
    "BY": ["ru_RU"],
    "CD": ["fr_BE", "ha_NG", "ig_NG", "yo_NG"],
    "CU": ["es_AR", "es_CL", "es_CO", "es_MX"],
    "GA": ["fr_BE", "ha_NG", "ig_NG", "yo_NG"],
    "HK": ["zh_TW"],
    "MG": ["fr_DZ"],
    "MN": ["uk_UA"],
    "RS": ["uk_UA", "ru_RU", "hu_HU"],
    "TG": ["fr_BE", "ha_NG", "ig_NG", "yo_NG"],
    "TZ": ["en_NG", "ha_NG", "ig_NG", "yo_NG"],
}
