# Generated by Django 5.1.8 on 2025-04-29 10:13

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('hero_block', 4), ('heading_block', 6), ('paragraph_block', 7), ('image_block', 10), ('embed_block', 11)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'blank': True, 'required': False}), 2: ('wagtail.blocks.DateBlock', (), {'blank': True, 'required': False}), 3: ('wagtail.images.blocks.ImageBlock', [], {'blank': True}), 4: ('wagtail.blocks.StructBlock', [[('title', 0), ('dates', 1), ('start_date', 2), ('end_date', 2), ('location', 1), ('background', 3)]], {}), 5: ('wagtail.blocks.ChoiceBlock', [], {'blank': True, 'choices': [('', 'Select a heading size'), ('h2', 'H2'), ('h3', 'H3'), ('h4', 'H4')], 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('heading_text', 0), ('size', 5)]], {}), 7: ('wagtail.blocks.RichTextBlock', (), {'icon': 'pilcrow'}), 8: ('wagtail.images.blocks.ImageBlock', [], {}), 9: ('wagtail.blocks.CharBlock', (), {'required': False}), 10: ('wagtail.blocks.StructBlock', [[('image', 8), ('caption', 9), ('attribution', 9)]], {}), 11: ('wagtail.embeds.blocks.EmbedBlock', (), {'help_text': 'Insert a URL to embed. For example, https://www.youtube.com/watch?v=SGJFWirQ3ks', 'icon': 'media'})}, help_text='Use this section to list UK pros.'),
        ),
    ]
