# Generated by Django 5.2 on 2025-05-13 20:16

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_homepage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('hero_block', 11), ('heading_block', 13), ('paragraph_block', 14), ('image_block', 17), ('embed_block', 18)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'blank': True, 'required': False}), 2: ('wagtail.blocks.DateBlock', (), {'blank': True, 'required': False}), 3: ('wagtail.images.blocks.ImageBlock', [], {'blank': True}), 4: ('wagtail.blocks.URLBlock', (), {'help_text': 'Link to another website page', 'required': False}), 5: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'Link to a page', 'required': False}), 6: ('wagtail.blocks.CharBlock', (), {'help_text': 'Text to display in the button', 'required': True}), 7: ('wagtail.blocks.StructBlock', [[('url', 4), ('page', 5), ('text', 6)]], {'blank': True, 'required': False}), 8: ('wagtail.blocks.CharBlock', (), {'help_text': 'Countdown title', 'required': True}), 9: ('wagtail.blocks.CharBlock', (), {'help_text': 'Countdown sub-title (actually above)', 'required': False}), 10: ('wagtail.blocks.StructBlock', [[('title', 8), ('subtitle', 9)]], {'blank': True, 'required': False}), 11: ('wagtail.blocks.StructBlock', [[('title', 0), ('dates', 1), ('start_date', 2), ('end_date', 2), ('location', 1), ('background', 3), ('call_to_action', 7), ('countdown', 10)]], {}), 12: ('wagtail.blocks.ChoiceBlock', [], {'blank': True, 'choices': [('', 'Select a heading size'), ('h2', 'H2'), ('h3', 'H3'), ('h4', 'H4')], 'required': False}), 13: ('wagtail.blocks.StructBlock', [[('heading_text', 0), ('size', 12)]], {}), 14: ('wagtail.blocks.RichTextBlock', (), {'icon': 'pilcrow'}), 15: ('wagtail.images.blocks.ImageBlock', [], {}), 16: ('wagtail.blocks.CharBlock', (), {'required': False}), 17: ('wagtail.blocks.StructBlock', [[('image', 15), ('caption', 16), ('attribution', 16)]], {}), 18: ('wagtail.embeds.blocks.EmbedBlock', (), {'help_text': 'Insert a URL to embed. For example, https://www.youtube.com/watch?v=SGJFWirQ3ks', 'icon': 'media'})}, help_text='Use this section to list UK pros.'),
        ),
    ]
