# Generated by Django 5.2.10 on 2026-01-24 20:06

import apps.base.models
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0014_alter_homepage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("hero_block", 11),
                    ("presentation_block", 16),
                    ("perks_block", 25),
                    ("about_block", 34),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"form_classname": "title", "required": True},
                    ),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"blank": True, "required": False},
                    ),
                    2: (
                        "wagtail.blocks.DateBlock",
                        (),
                        {"blank": True, "required": False},
                    ),
                    3: ("wagtail.images.blocks.ImageBlock", [], {"blank": True}),
                    4: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Link to another website page",
                            "required": False,
                        },
                    ),
                    5: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"help_text": "Link to a page", "required": False},
                    ),
                    6: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Text to display in the button",
                            "required": True,
                        },
                    ),
                    7: (
                        "wagtail.blocks.StructBlock",
                        [[("url", 4), ("page", 5), ("text", 6)]],
                        {"blank": True, "required": False},
                    ),
                    8: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Countdown title", "required": True},
                    ),
                    9: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Countdown sub-title (actually above)",
                            "required": False,
                        },
                    ),
                    10: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 8), ("subtitle", 9)]],
                        {"blank": True, "required": False},
                    ),
                    11: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 0),
                                ("dates", 1),
                                ("start_date", 2),
                                ("end_date", 2),
                                ("location", 1),
                                ("background", 3),
                                ("call_to_action", 7),
                                ("countdown", 10),
                            ]
                        ],
                        {},
                    ),
                    12: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"form_classname": "subtitle", "required": True},
                    ),
                    13: ("wagtail.images.blocks.ImageBlock", [], {}),
                    14: ("wagtail.blocks.RichTextBlock", (), {"icon": "pilcrow"}),
                    15: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Text on the More button", "required": False},
                    ),
                    16: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 0),
                                ("subtitle", 12),
                                ("main_image", 13),
                                ("first_image", 13),
                                ("second_image", 13),
                                ("third_image", 13),
                                ("paragraph", 14),
                                ("button_text", 15),
                                ("button_page", 5),
                            ]
                        ],
                        {},
                    ),
                    17: ("apps.base.blocks.VideoBlock", (), {}),
                    18: ("wagtail.blocks.StreamBlock", [[("video", 17)]], {}),
                    19: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "form_classname": "title",
                            "label": "Titolo",
                            "required": True,
                        },
                    ),
                    20: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"icon": "pilcrow", "label": "Teksto"},
                    ),
                    21: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": apps.base.models.FontAwesomeIcon.get_icon_choices,
                            "label": "Simbolo",
                        },
                    ),
                    22: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("", "(elektu koloron)"),
                                ("sky", "Blua"),
                                ("emerald", "Verda"),
                                ("amber", "Flava"),
                                ("orange", "Oranĝa"),
                                ("rose", "Rozkolora"),
                                ("indigo", "Violkolora"),
                            ],
                            "label": "Koloro",
                        },
                    ),
                    23: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 19),
                                ("paragraph", 20),
                                ("icon", 21),
                                ("color", 22),
                            ]
                        ],
                        {"blank": True, "required": False},
                    ),
                    24: ("wagtail.blocks.StreamBlock", [[("perk", 23)]], {}),
                    25: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 0),
                                ("background", 3),
                                ("videos", 18),
                                ("perks", 24),
                            ]
                        ],
                        {},
                    ),
                    26: ("wagtail.blocks.CharBlock", (), {}),
                    27: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": apps.base.models.FontAwesomeIcon.get_icon_choices},
                    ),
                    28: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 26), ("description", 26), ("icon", 27)]],
                        {"blank": True, "required": False},
                    ),
                    29: (
                        "wagtail.blocks.StreamBlock",
                        [[("fact", 28)]],
                        {"blank": True, "required": False},
                    ),
                    30: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"required": True},
                    ),
                    31: (
                        "wagtail.blocks.StreamBlock",
                        [[("image", 30)]],
                        {"blank": True, "required": False},
                    ),
                    32: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"blank": True, "required": False},
                    ),
                    33: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"blank": True, "required": False},
                    ),
                    34: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 1),
                                ("subtitle", 1),
                                ("facts", 29),
                                ("pictures", 31),
                                ("event_map", 32),
                                ("directions", 33),
                            ]
                        ],
                        {},
                    ),
                },
                help_text="Use this section to list UK pros.",
            ),
        ),
    ]
