# Generated by Django 6.0.2 on 2026-02-18 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_registrationpage_vue_module'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegistrationPage',
        ),
    ]
