# Generated by Django 5.2.8 on 2025-11-22 20:25

import apps.base.models
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0012_alter_homepage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("hero_block", 11),
                    ("presentation_block", 16),
                    ("perks_block", 22),
                    ("about_block", 31),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"form_classname": "title", "required": True},
                    ),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"blank": True, "required": False},
                    ),
                    2: (
                        "wagtail.blocks.DateBlock",
                        (),
                        {"blank": True, "required": False},
                    ),
                    3: ("wagtail.images.blocks.ImageBlock", [], {"blank": True}),
                    4: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Link to another website page",
                            "required": False,
                        },
                    ),
                    5: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"help_text": "Link to a page", "required": False},
                    ),
                    6: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Text to display in the button",
                            "required": True,
                        },
                    ),
                    7: (
                        "wagtail.blocks.StructBlock",
                        [[("url", 4), ("page", 5), ("text", 6)]],
                        {"blank": True, "required": False},
                    ),
                    8: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Countdown title", "required": True},
                    ),
                    9: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Countdown sub-title (actually above)",
                            "required": False,
                        },
                    ),
                    10: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 8), ("subtitle", 9)]],
                        {"blank": True, "required": False},
                    ),
                    11: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 0),
                                ("dates", 1),
                                ("start_date", 2),
                                ("end_date", 2),
                                ("location", 1),
                                ("background", 3),
                                ("call_to_action", 7),
                                ("countdown", 10),
                            ]
                        ],
                        {},
                    ),
                    12: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"form_classname": "subtitle", "required": True},
                    ),
                    13: ("wagtail.images.blocks.ImageBlock", [], {}),
                    14: ("wagtail.blocks.RichTextBlock", (), {"icon": "pilcrow"}),
                    15: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Text on the More button", "required": False},
                    ),
                    16: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 0),
                                ("subtitle", 12),
                                ("main_image", 13),
                                ("first_image", 13),
                                ("second_image", 13),
                                ("third_image", 13),
                                ("paragraph", 14),
                                ("button_text", 15),
                                ("button_page", 5),
                            ]
                        ],
                        {},
                    ),
                    17: (
                        "wagtail.embeds.blocks.EmbedBlock",
                        (),
                        {
                            "help_text": "Insert a URL to embed. For example, https://www.youtube.com/watch?v=xm4qTLcXKc4",
                            "icon": "media",
                            "max_height": 360,
                            "max_width": 640,
                        },
                    ),
                    18: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": apps.base.models.FontAwesomeIcon.get_icon_choices},
                    ),
                    19: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("", "Select a color"),
                                ("warning", "Yellow"),
                                ("info", "Blue"),
                                ("success", "Green"),
                                ("secondary", "Pink"),
                            ]
                        },
                    ),
                    20: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 0),
                                ("paragraph", 14),
                                ("icon", 18),
                                ("color", 19),
                            ]
                        ],
                        {"blank": True, "required": False},
                    ),
                    21: ("wagtail.blocks.StreamBlock", [[("perk", 20)]], {}),
                    22: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("background", 3),
                                ("embed_block", 17),
                                ("title", 0),
                                ("perks", 21),
                            ]
                        ],
                        {},
                    ),
                    23: ("wagtail.blocks.CharBlock", (), {}),
                    24: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("", "Select an icon"),
                                ("fa-solid fa-users", "Group"),
                                ("fa-regular fa-square", "Square"),
                                ("fa-regular fa-clock", "Clock"),
                                ("fa-solid fa-cloud-sun", "Weather"),
                                ("fa-regular fa-comment", "Speech"),
                                ("fa-solid fa-coins", "Currencies"),
                                ("fa-solid fa-plug-circle-bolt", "Electricity"),
                                ("fa-solid fa-water", "Water"),
                                ("fa-solid fa-phone", "Phone"),
                            ]
                        },
                    ),
                    25: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 23), ("description", 23), ("icon", 24)]],
                        {"blank": True, "required": False},
                    ),
                    26: (
                        "wagtail.blocks.StreamBlock",
                        [[("fact", 25)]],
                        {"blank": True, "required": False},
                    ),
                    27: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"required": True},
                    ),
                    28: (
                        "wagtail.blocks.StreamBlock",
                        [[("image", 27)]],
                        {"blank": True, "required": False},
                    ),
                    29: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {"blank": True, "required": False},
                    ),
                    30: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"blank": True, "required": False},
                    ),
                    31: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 1),
                                ("subtitle", 1),
                                ("facts", 26),
                                ("pictures", 28),
                                ("event_map", 29),
                                ("directions", 30),
                            ]
                        ],
                        {},
                    ),
                },
                help_text="Use this section to list UK pros.",
            ),
        ),
    ]
