# Generated by Django 6.0.2 on 2026-02-18 14:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0015_alter_homepage_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="registrationpage",
            name="vue_module",
            field=models.CharField(
                choices=[("registration", "Aliĝilo"), ("edit", "Redaktilo")],
                default="registration",
                max_length=12,
            ),
        ),
    ]
