# Generated by Django 6.0.3 on 2026-04-20 09:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0018_basicpage_header_image"),
        ("wagtailcore", "0096_referenceindex_referenceindex_source_object_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="HomePage",
            new_name="UkHomePage",
        ),
    ]
