# Generated by Django 6.0.8 on 2026-10-02 15:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0019_rename_homepage_ukhomepage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ukhomepage",
            name="page_ptr",
        ),
        migrations.DeleteModel(
            name="BasicPage",
        ),
        migrations.DeleteModel(
            name="UkHomePage",
        ),
    ]
