# Generated by Django 6.0.3 on 2026-04-15 09:49

import django.db.models.deletion
import evente.blocks.components
import evente.blocks.headers
import wagtail.fields
import wagtailmenus.models.menus
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("wagtailcore", "0096_referenceindex_referenceindex_source_object_and_more"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventeFooter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bg_color",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("red", "Red"),
                            ("orange", "Orange"),
                            ("amber", "Amber"),
                            ("yellow", "Yellow"),
                            ("lime", "Lime"),
                            ("green", "Green"),
                            ("emerald", "Emerald"),
                            ("teal", "Teal"),
                            ("cyan", "Cyan"),
                            ("sky", "Sky"),
                            ("blue", "Blue"),
                            ("indigo", "Indigo"),
                            ("violet", "Violet"),
                            ("purple", "Purple"),
                            ("fuchsia", "Fuchsia"),
                            ("pink", "Pink"),
                            ("rose", "Rose"),
                            ("slate", "Slate"),
                            ("gray", "Gray"),
                            ("zinc", "Zinc"),
                            ("neutral", "Neutral"),
                            ("stone", "Stone"),
                            ("taupe", "Taupe"),
                            ("mauve", "Mauve"),
                            ("mist", "Mist"),
                            ("olive", "Olive"),
                        ],
                        verbose_name="Color",
                    ),
                ),
                (
                    "bg_lightness",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (50, "50"),
                            (100, "100"),
                            (200, "200"),
                            (300, "300"),
                            (400, "400"),
                            (500, "500"),
                            (600, "600"),
                            (700, "700"),
                            (800, "800"),
                            (900, "900"),
                            (950, "950"),
                        ],
                        null=True,
                        verbose_name="Lightness",
                    ),
                ),
                (
                    "bg_position",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("bg-top-left", "Top left"),
                            ("bg-top", "Top"),
                            ("bg-top-right", "Top right"),
                            ("bg-left", "Left"),
                            ("bg-center", "Center"),
                            ("bg-right", "Right"),
                            ("bg-bottom-left", "Bottom left"),
                            ("bg-bottom", "Bottom"),
                            ("bg-bottom-right", "Bottom right"),
                        ],
                        default="bg-center",
                        verbose_name="Position",
                    ),
                ),
                (
                    "bg_repeat",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("bg-repeat", "Repeat"),
                            ("bg-repeat-x", "X"),
                            ("bg-repeat-y", "Y"),
                            ("bg-repeat-space", "Space"),
                            ("bg-repeat-round", "Round"),
                            ("bg-no-repeat", "No repeat"),
                        ],
                        default="bg-no-repeat",
                        verbose_name="Repeat",
                    ),
                ),
                (
                    "bg_size",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("bg-auto", "Auto"),
                            ("bg-cover", "Cover"),
                            ("bg-contain", "Contain"),
                        ],
                        default="bg-cover",
                        verbose_name="Size",
                    ),
                ),
                (
                    "margin_top",
                    models.CharField(
                        blank=True,
                        choices=[("mt-[-95px]", "-95px")],
                        default="",
                        verbose_name="Margin top",
                    ),
                ),
                (
                    "padding_top",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pt-[80px]", "80px"),
                            ("pt-[110px] max-2xl:!pt-[70px]", "110px"),
                            ("pt-[130px] max-2xl:!pt-[90px]", "130px"),
                            ("pt-[155px] max-2xl:!pt-[100px]", "155px"),
                            ("pt-[200px]", "200px"),
                        ],
                        default="pt-[130px] max-2xl:!pt-[90px]",
                        verbose_name="Padding top",
                    ),
                ),
                (
                    "content",
                    wagtail.fields.StreamField(
                        [("simple", 25), ("two_colors", 26), ("three_rows", 26)],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"default": "", "label": "Link", "required": False},
                            ),
                            1: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                            2: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("mt-0", "None"),
                                        ("mt-3", "3"),
                                        ("mt-6", "6"),
                                    ],
                                    "label": "Top margin",
                                    "required": False,
                                },
                            ),
                            3: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("mb-0", "None"),
                                        ("mb-3", "3"),
                                        ("mb-6", "6"),
                                    ],
                                    "label": "Bottom margin",
                                    "required": False,
                                },
                            ),
                            4: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [("", "Normal"), ("text-xl", "Big")],
                                    "label": "Text size",
                                    "required": False,
                                },
                            ),
                            5: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("", "Normal"),
                                        ("font-semibold", "Semibold"),
                                        ("font-bold", "Bold"),
                                    ],
                                    "label": "Text weight",
                                    "required": False,
                                },
                            ),
                            6: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("red", "Red"),
                                        ("orange", "Orange"),
                                        ("amber", "Amber"),
                                        ("yellow", "Yellow"),
                                        ("lime", "Lime"),
                                        ("green", "Green"),
                                        ("emerald", "Emerald"),
                                        ("teal", "Teal"),
                                        ("cyan", "Cyan"),
                                        ("sky", "Sky"),
                                        ("blue", "Blue"),
                                        ("indigo", "Indigo"),
                                        ("violet", "Violet"),
                                        ("purple", "Purple"),
                                        ("fuchsia", "Fuchsia"),
                                        ("pink", "Pink"),
                                        ("rose", "Rose"),
                                        ("slate", "Slate"),
                                        ("gray", "Gray"),
                                        ("zinc", "Zinc"),
                                        ("neutral", "Neutral"),
                                        ("stone", "Stone"),
                                        ("taupe", "Taupe"),
                                        ("mauve", "Mauve"),
                                        ("mist", "Mist"),
                                        ("olive", "Olive"),
                                    ],
                                    "label": "Text color",
                                },
                            ),
                            7: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        (50, "50"),
                                        (100, "100"),
                                        (200, "200"),
                                        (300, "300"),
                                        (400, "400"),
                                        (500, "500"),
                                        (600, "600"),
                                        (700, "700"),
                                        (800, "800"),
                                        (900, "900"),
                                        (950, "950"),
                                    ],
                                    "label": "Text lightness",
                                },
                            ),
                            8: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("href", 0),
                                        ("logo", 1),
                                        ("margin_top", 2),
                                        ("margin_bottom", 3),
                                        ("text_size", 4),
                                        ("text_weight", 5),
                                        ("text_color", 6),
                                        ("text_lightness", 7),
                                    ]
                                ],
                                {"label": "Logo"},
                            ),
                            9: ("wagtail.blocks.CharBlock", (), {"label": "Text"}),
                            10: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("text", 9),
                                        ("margin_top", 2),
                                        ("margin_bottom", 3),
                                        ("text_size", 4),
                                        ("text_weight", 5),
                                        ("text_color", 6),
                                        ("text_lightness", 7),
                                    ]
                                ],
                                {"label": "Text"},
                            ),
                            11: ("wagtail.blocks.CharBlock", (), {"label": "Link"}),
                            12: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("href", 11),
                                        ("text", 9),
                                        ("margin_top", 2),
                                        ("margin_bottom", 3),
                                        ("text_size", 4),
                                        ("text_weight", 5),
                                        ("text_color", 6),
                                        ("text_lightness", 7),
                                    ]
                                ],
                                {"label": "Link"},
                            ),
                            13: (
                                "evente.blocks.footers.FlatMenuChooserBlock",
                                (),
                                {
                                    "label": "Flat menu",
                                    "target_model": wagtailmenus.models.menus.FlatMenu,
                                },
                            ),
                            14: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("menu", 13),
                                        ("margin_top", 2),
                                        ("margin_bottom", 3),
                                        ("text_size", 4),
                                        ("text_weight", 5),
                                        ("text_color", 6),
                                        ("text_lightness", 7),
                                    ]
                                ],
                                {"label": "Menu"},
                            ),
                            15: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "default": "Images",
                                    "label": "Title",
                                    "required": False,
                                },
                            ),
                            16: (
                                "wagtail.blocks.ListBlock",
                                (1,),
                                {"label": "Images", "required": False},
                            ),
                            17: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("title", 15),
                                        ("images", 16),
                                        ("margin_top", 2),
                                        ("margin_bottom", 3),
                                        ("text_size", 4),
                                        ("text_weight", 5),
                                        ("text_color", 6),
                                        ("text_lightness", 7),
                                    ]
                                ],
                                {"label": "Mini gallery"},
                            ),
                            18: (
                                "wagtail.blocks.StreamBlock",
                                [
                                    [
                                        ("logo", 8),
                                        ("text", 10),
                                        ("link", 12),
                                        ("menu", 14),
                                        ("mini_gallery", 17),
                                    ]
                                ],
                                {
                                    "collapsed": True,
                                    "label": "Content",
                                    "required": False,
                                },
                            ),
                            19: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("w-1/12", "1/12"),
                                        ("w-2/12", "2/12 Sixth"),
                                        ("w-3/12", "3/12 Fourth"),
                                        ("w-4/12", "4/12 Third"),
                                        ("w-5/12", "5/12"),
                                        ("w-6/12", "6/12 Half"),
                                        ("w-7/12", "7/12"),
                                        ("w-8/12", "8/12 Two thirds"),
                                        ("w-9/12", "9/12 Three fourths"),
                                        ("w-10/12", "10/12"),
                                        ("w-11/12", "11/12"),
                                        ("w-12/12", "12/12 Full width"),
                                    ],
                                    "label": "Width XL",
                                },
                            ),
                            20: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("w-1/12", "1/12"),
                                        ("w-2/12", "2/12 Sixth"),
                                        ("w-3/12", "3/12 Fourth"),
                                        ("w-4/12", "4/12 Third"),
                                        ("w-5/12", "5/12"),
                                        ("w-6/12", "6/12 Half"),
                                        ("w-7/12", "7/12"),
                                        ("w-8/12", "8/12 Two thirds"),
                                        ("w-9/12", "9/12 Three fourths"),
                                        ("w-10/12", "10/12"),
                                        ("w-11/12", "11/12"),
                                        ("w-12/12", "12/12 Full width"),
                                    ],
                                    "label": "Width LG",
                                },
                            ),
                            21: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("w-1/12", "1/12"),
                                        ("w-2/12", "2/12 Sixth"),
                                        ("w-3/12", "3/12 Fourth"),
                                        ("w-4/12", "4/12 Third"),
                                        ("w-5/12", "5/12"),
                                        ("w-6/12", "6/12 Half"),
                                        ("w-7/12", "7/12"),
                                        ("w-8/12", "8/12 Two thirds"),
                                        ("w-9/12", "9/12 Three fourths"),
                                        ("w-10/12", "10/12"),
                                        ("w-11/12", "11/12"),
                                        ("w-12/12", "12/12 Full width"),
                                    ],
                                    "label": "Width MD",
                                },
                            ),
                            22: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("content", 18),
                                        ("width_xl", 19),
                                        ("width_lg", 20),
                                        ("width_md", 21),
                                    ]
                                ],
                                {},
                            ),
                            23: ("wagtail.blocks.ListBlock", (22,), {}),
                            24: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "default": "© ",
                                    "label": "Copyright",
                                    "required": False,
                                },
                            ),
                            25: (
                                "wagtail.blocks.StructBlock",
                                [[("columns", 23), ("copyright_text", 24)]],
                                {},
                            ),
                            26: ("wagtail.blocks.StructBlock", [[("columns", 23)]], {}),
                        },
                    ),
                ),
                (
                    "bg_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="wagtailimages.image",
                        verbose_name="image",
                    ),
                ),
                (
                    "site",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wagtailcore.site",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EventeHeader",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sections",
                    wagtail.fields.StreamField(
                        [
                            ("top", 8),
                            ("main", 27),
                            ("mobile", 35),
                            ("search_panel", 36),
                            ("cart_panel", 36),
                            ("right_panel", 36),
                        ],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"default": "Top", "label": "Name"},
                            ),
                            1: ("wagtail.blocks.CharBlock", (), {"label": "Text"}),
                            2: ("wagtail.blocks.CharBlock", (), {"label": "Link"}),
                            3: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("flaticon-account", "Account"),
                                        ("flaticon-announcement", "Announcement"),
                                        ("flaticon-calendar", "Calendar"),
                                        ("flaticon-chat-box", "Chat box"),
                                        ("flaticon-deal", "Deal"),
                                        ("flaticon-fastfood", "Fastfood"),
                                        ("flaticon-gps", "GPS"),
                                        ("flaticon-handshake", "Handshake"),
                                        ("flaticon-mail", "Mail"),
                                        ("flaticon-meeting", "Meeting"),
                                        ("flaticon-megaphone", "Megaphone"),
                                        ("flaticon-phone", "Phone"),
                                        ("flaticon-plus", "Plus"),
                                        ("flaticon-puzzle", "Puzzle"),
                                        ("flaticon-request", "Request"),
                                        ("flaticon-search", "Search"),
                                        ("flaticon-share", "Share"),
                                        ("flaticon-shopping-cart", "Shopping cart"),
                                        ("flaticon-speaker", "Speaker"),
                                        ("flaticon-surprise", "Surprise"),
                                        ("flaticon-teamwork", "Teamwork"),
                                        ("flaticon-teamwork-1", "Teamwork 1"),
                                        ("flaticon-teamwork-2", "Teamwork 2"),
                                        ("flaticon-time", "Time"),
                                        ("flaticon-up-right-arrow", "Up right arrow"),
                                        (
                                            "flaticon-up-right-arrow-1",
                                            "Up right arrow 1",
                                        ),
                                    ],
                                    "label": "Flaticon",
                                    "max_length": 30,
                                    "required": False,
                                },
                            ),
                            4: (
                                "wagtail.blocks.StructBlock",
                                [[("text", 1), ("link", 2), ("flaticon", 3)]],
                                {},
                            ),
                            5: ("evente.blocks.headers.HeaderSocialMedia", (), {}),
                            6: (
                                "wagtail.blocks.StreamBlock",
                                [[("contact", 4), ("social_media", 5)]],
                                {"label": "Left items", "required": False},
                            ),
                            7: (
                                "wagtail.blocks.StreamBlock",
                                [[("contact", 4), ("social_media", 5)]],
                                {"label": "Right items", "required": False},
                            ),
                            8: (
                                "wagtail.blocks.StructBlock",
                                [[("name", 0), ("left", 6), ("right", 7)]],
                                {"label": "Top header"},
                            ),
                            9: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"default": "Main", "label": "Name"},
                            ),
                            10: (
                                "wagtail.blocks.PageChooserBlock",
                                (),
                                {
                                    "default": evente.blocks.headers.default_home_page,
                                    "label": "Home page",
                                },
                            ),
                            11: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "default": "150px",
                                    "help_text": "CSS value, like '150px' or 'auto'",
                                    "label": "Width",
                                },
                            ),
                            12: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "default": "auto",
                                    "help_text": "CSS value, like '150px' or 'auto'",
                                    "label": "Height",
                                },
                            ),
                            13: (
                                "wagtail.blocks.StructBlock",
                                [[("page", 10), ("width", 11), ("height", 12)]],
                                {},
                            ),
                            14: ("evente.blocks.headers.HeaderMainMenu", (), {}),
                            15: ("evente.blocks.headers.HeaderSearch", (), {}),
                            16: ("evente.blocks.headers.HeaderCart", (), {}),
                            17: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Text to display in the button",
                                    "required": True,
                                },
                            ),
                            18: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Anchor or link to another website page",
                                    "required": False,
                                    "validators": [
                                        evente.blocks.components.fragment_validator
                                    ],
                                },
                            ),
                            19: (
                                "wagtail.blocks.PageChooserBlock",
                                (),
                                {"help_text": "Link to a page", "required": False},
                            ),
                            20: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("-", "None"),
                                        ("arrow-top-right", "arrow top right"),
                                    ],
                                    "icon": "arrow-right-full",
                                    "label": "Icon at the end",
                                    "required": False,
                                },
                            ),
                            21: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("text", 17),
                                        ("url", 18),
                                        ("page", 19),
                                        ("append_icon", 20),
                                    ]
                                ],
                                {},
                            ),
                            22: ("evente.blocks.headers.HeaderMobileButton", (), {}),
                            23: (
                                "wagtail.blocks.StreamBlock",
                                [
                                    [
                                        ("logo", 13),
                                        ("main_menu", 14),
                                        ("search", 15),
                                        ("cart", 16),
                                        ("call_to_action", 21),
                                        ("mobile_button", 22),
                                    ]
                                ],
                                {"label": "Left items", "required": False},
                            ),
                            24: (
                                "wagtail.blocks.StreamBlock",
                                [
                                    [
                                        ("logo", 13),
                                        ("main_menu", 14),
                                        ("search", 15),
                                        ("cart", 16),
                                        ("call_to_action", 21),
                                        ("mobile_button", 22),
                                    ]
                                ],
                                {"label": "Center items", "required": False},
                            ),
                            25: (
                                "wagtail.blocks.StreamBlock",
                                [
                                    [
                                        ("logo", 13),
                                        ("main_menu", 14),
                                        ("search", 15),
                                        ("cart", 16),
                                        ("call_to_action", 21),
                                        ("mobile_button", 22),
                                    ]
                                ],
                                {"label": "Right items", "required": False},
                            ),
                            26: (
                                "wagtail.blocks.StreamBlock",
                                [
                                    [
                                        ("logo", 13),
                                        ("main_menu", 14),
                                        ("search", 15),
                                        ("cart", 16),
                                        ("call_to_action", 21),
                                        ("mobile_button", 22),
                                    ]
                                ],
                                {"label": "End items", "required": False},
                            ),
                            27: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("name", 9),
                                        ("left", 23),
                                        ("center", 24),
                                        ("right", 25),
                                        ("end", 26),
                                    ]
                                ],
                                {"label": "Main header"},
                            ),
                            28: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"default": "Mobile", "label": "Name"},
                            ),
                            29: (
                                "wagtail.blocks.PageChooserBlock",
                                (),
                                {"label": "Search page"},
                            ),
                            30: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"default": "Search here…", "label": "Name"},
                            ),
                            31: (
                                "wagtail.blocks.StructBlock",
                                [[("page", 29), ("text", 30)]],
                                {},
                            ),
                            32: ("evente.blocks.headers.HeaderMobileMainMenu", (), {}),
                            33: (
                                "evente.blocks.headers.HeaderMobileSocialMedia",
                                (),
                                {},
                            ),
                            34: (
                                "wagtail.blocks.StreamBlock",
                                [
                                    [
                                        ("logo", 13),
                                        ("search", 31),
                                        ("main_menu", 32),
                                        ("call_to_action", 21),
                                        ("social_media", 33),
                                    ]
                                ],
                                {"label": "Items", "required": False},
                            ),
                            35: (
                                "wagtail.blocks.StructBlock",
                                [[("name", 28), ("items", 34)]],
                                {"label": ""},
                            ),
                            36: ("evente.models.Dummy", (), {"label": ""}),
                        },
                    ),
                ),
                (
                    "show_top_on_homepage",
                    models.BooleanField(
                        default=False, verbose_name="Show top on homepage"
                    ),
                ),
                (
                    "site",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wagtailcore.site",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EventeSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "primary_color",
                    models.CharField(
                        choices=[
                            ("red", "Red"),
                            ("orange", "Orange"),
                            ("amber", "Amber"),
                            ("yellow", "Yellow"),
                            ("lime", "Lime"),
                            ("green", "Green"),
                            ("emerald", "Emerald"),
                            ("teal", "Teal"),
                            ("cyan", "Cyan"),
                            ("sky", "Sky"),
                            ("blue", "Blue"),
                            ("indigo", "Indigo"),
                            ("violet", "Violet"),
                            ("purple", "Purple"),
                            ("fuchsia", "Fuchsia"),
                            ("pink", "Pink"),
                            ("rose", "Rose"),
                            ("slate", "Slate"),
                            ("gray", "Gray"),
                            ("zinc", "Zinc"),
                            ("neutral", "Neutral"),
                            ("stone", "Stone"),
                            ("taupe", "Taupe"),
                            ("mauve", "Mauve"),
                            ("mist", "Mist"),
                            ("olive", "Olive"),
                        ],
                        default="indigo",
                        verbose_name="primary color",
                    ),
                ),
                (
                    "primary_lightness",
                    models.IntegerField(
                        choices=[
                            (50, "50"),
                            (100, "100"),
                            (200, "200"),
                            (300, "300"),
                            (400, "400"),
                            (500, "500"),
                            (600, "600"),
                            (700, "700"),
                            (800, "800"),
                            (900, "900"),
                            (950, "950"),
                        ],
                        default=500,
                        verbose_name="primary lightness",
                    ),
                ),
                (
                    "secondary_color",
                    models.CharField(
                        choices=[
                            ("red", "Red"),
                            ("orange", "Orange"),
                            ("amber", "Amber"),
                            ("yellow", "Yellow"),
                            ("lime", "Lime"),
                            ("green", "Green"),
                            ("emerald", "Emerald"),
                            ("teal", "Teal"),
                            ("cyan", "Cyan"),
                            ("sky", "Sky"),
                            ("blue", "Blue"),
                            ("indigo", "Indigo"),
                            ("violet", "Violet"),
                            ("purple", "Purple"),
                            ("fuchsia", "Fuchsia"),
                            ("pink", "Pink"),
                            ("rose", "Rose"),
                            ("slate", "Slate"),
                            ("gray", "Gray"),
                            ("zinc", "Zinc"),
                            ("neutral", "Neutral"),
                            ("stone", "Stone"),
                            ("taupe", "Taupe"),
                            ("mauve", "Mauve"),
                            ("mist", "Mist"),
                            ("olive", "Olive"),
                        ],
                        default="pink",
                        verbose_name="secondary color",
                    ),
                ),
                (
                    "secondary_lightness",
                    models.IntegerField(
                        choices=[
                            (50, "50"),
                            (100, "100"),
                            (200, "200"),
                            (300, "300"),
                            (400, "400"),
                            (500, "500"),
                            (600, "600"),
                            (700, "700"),
                            (800, "800"),
                            (900, "900"),
                            (950, "950"),
                        ],
                        default=400,
                        verbose_name="secondary lightness",
                    ),
                ),
                (
                    "social_media",
                    wagtail.fields.StreamField(
                        [("link", 4)],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"default": "", "label": "Name"},
                            ),
                            1: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "default": "#",
                                    "label": "Link",
                                    "validators": [
                                        evente.blocks.components.fragment_validator
                                    ],
                                },
                            ),
                            2: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("fa-regular", "Regular"),
                                        ("fa-light", "Light"),
                                        ("fa-brands", "Brands"),
                                        ("fa-solid", "Solid"),
                                    ],
                                    "label": "Font Awesome style",
                                },
                            ),
                            3: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "default": "fa-globe",
                                    "help_text": "https://fontawesome.com/v6/search?ic=free-collection",
                                    "label": "Font Awesome name",
                                },
                            ),
                            4: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("name", 0),
                                        ("href", 1),
                                        ("fa_style", 2),
                                        ("fa_name", 3),
                                    ]
                                ],
                                {},
                            ),
                        },
                    ),
                ),
                (
                    "logo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                        verbose_name="logo",
                    ),
                ),
                (
                    "logo_monochrome",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                        verbose_name="logo monochrome",
                    ),
                ),
                (
                    "site",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wagtailcore.site",
                    ),
                ),
            ],
            options={
                "verbose_name": "Evente settings",
            },
        ),
    ]
