# Generated by Django 6.0.3 on 2026-04-22 11:14

import evente.blocks.components
import evente.blocks.headers
import wagtail.fields
import wagtailmenus.models.menus
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("evente", "0002_alter_eventefooter_bg_color_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventefooter",
            name="content",
            field=wagtail.fields.StreamField(
                [("simple", 28), ("two_colors", 29), ("three_rows", 29)],
                blank=True,
                block_lookup={
                    0: ("wagtail.images.blocks.ImageChooserBlock", (), {}),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "", "label": "Link", "required": False},
                    ),
                    2: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "_setting": True,
                            "choices": [("mt-0", "None"), ("mt-3", "3"), ("mt-6", "6")],
                            "label": "Top margin",
                            "required": False,
                        },
                    ),
                    3: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "_setting": True,
                            "choices": [("mb-0", "None"), ("mb-3", "3"), ("mb-6", "6")],
                            "label": "Bottom margin",
                            "required": False,
                        },
                    ),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("logo", 0),
                                ("href", 1),
                                ("margin_top", 2),
                                ("margin_bottom", 3),
                            ]
                        ],
                        {"label": "Logo"},
                    ),
                    5: ("wagtail.blocks.CharBlock", (), {"label": "Text"}),
                    6: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "_setting": True,
                            "choices": [
                                ("primary", "Primary"),
                                ("secondary", "Secondary"),
                                ("white", "White"),
                                ("black", "Black"),
                                ("red", "Red"),
                                ("orange", "Orange"),
                                ("amber", "Amber"),
                                ("yellow", "Yellow"),
                                ("lime", "Lime"),
                                ("green", "Green"),
                                ("emerald", "Emerald"),
                                ("teal", "Teal"),
                                ("cyan", "Cyan"),
                                ("sky", "Sky"),
                                ("blue", "Blue"),
                                ("indigo", "Indigo"),
                                ("violet", "Violet"),
                                ("purple", "Purple"),
                                ("fuchsia", "Fuchsia"),
                                ("pink", "Pink"),
                                ("rose", "Rose"),
                                ("slate", "Slate"),
                                ("gray", "Gray"),
                                ("zinc", "Zinc"),
                                ("neutral", "Neutral"),
                                ("stone", "Stone"),
                                ("taupe", "Taupe"),
                                ("mauve", "Mauve"),
                                ("mist", "Mist"),
                                ("olive", "Olive"),
                            ],
                            "label": "Color",
                        },
                    ),
                    7: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "_setting": True,
                            "choices": [
                                (50, "50"),
                                (100, "100"),
                                (200, "200"),
                                (300, "300"),
                                (400, "400"),
                                (500, "500"),
                                (600, "600"),
                                (700, "700"),
                                (800, "800"),
                                (900, "900"),
                                (950, "950"),
                            ],
                            "label": "Lightness",
                        },
                    ),
                    8: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "_setting": True,
                            "choices": [("", "Normal"), ("text-xl", "Big")],
                            "label": "Text size",
                            "required": False,
                        },
                    ),
                    9: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "_setting": True,
                            "choices": [
                                ("", "Normal"),
                                ("font-semibold", "Semibold"),
                                ("font-bold", "Bold"),
                            ],
                            "label": "Text weight",
                            "required": False,
                        },
                    ),
                    10: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("text", 5),
                                ("color", 6),
                                ("lightness", 7),
                                ("margin_top", 2),
                                ("margin_bottom", 3),
                                ("text_size", 8),
                                ("text_weight", 9),
                            ]
                        ],
                        {"label": "Text"},
                    ),
                    11: ("wagtail.blocks.CharBlock", (), {"label": "Link"}),
                    12: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("text", 5),
                                ("href", 11),
                                ("color", 6),
                                ("lightness", 7),
                                ("margin_top", 2),
                                ("margin_bottom", 3),
                                ("text_size", 8),
                                ("text_weight", 9),
                            ]
                        ],
                        {"label": "Link"},
                    ),
                    13: (
                        "evente.blocks.footers.FlatMenuChooserBlock",
                        (),
                        {
                            "label": "Flat menu",
                            "target_model": wagtailmenus.models.menus.FlatMenu,
                        },
                    ),
                    14: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("menu", 13),
                                ("color", 6),
                                ("lightness", 7),
                                ("margin_top", 2),
                                ("margin_bottom", 3),
                                ("text_size", 8),
                                ("text_weight", 9),
                            ]
                        ],
                        {"label": "Menu"},
                    ),
                    15: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Images", "label": "Title", "required": False},
                    ),
                    16: (
                        "wagtail.blocks.ListBlock",
                        (0,),
                        {"label": "Images", "required": False},
                    ),
                    17: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("title", 15),
                                ("images", 16),
                                ("color", 6),
                                ("lightness", 7),
                                ("margin_top", 2),
                                ("margin_bottom", 3),
                                ("text_size", 8),
                                ("text_weight", 9),
                            ]
                        ],
                        {"label": "Mini gallery"},
                    ),
                    18: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("logo", 4),
                                ("text", 10),
                                ("link", 12),
                                ("menu", 14),
                                ("mini_gallery", 17),
                            ]
                        ],
                        {"collapsed": True, "label": "Content", "required": False},
                    ),
                    19: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "_setting": True,
                            "choices": [
                                ("w-1/12", "1/12"),
                                ("w-1/6", "2/12"),
                                ("w-1/4", "3/12"),
                                ("w-1/3", "4/12"),
                                ("w-5/12", "5/12"),
                                ("w-1/2", "6/12"),
                                ("w-7/12", "7/12"),
                                ("w-2/3", "8/12"),
                                ("w-3/4", "9/12"),
                                ("w-5/6", "10/12"),
                                ("w-11/12", "11/12"),
                                ("w-full", "12/12"),
                            ],
                            "label": "Width (default)",
                            "required": False,
                        },
                    ),
                    20: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "_setting": True,
                            "choices": [
                                ("w-1/12", "1/12"),
                                ("w-1/6", "2/12"),
                                ("w-1/4", "3/12"),
                                ("w-1/3", "4/12"),
                                ("w-5/12", "5/12"),
                                ("w-1/2", "6/12"),
                                ("w-7/12", "7/12"),
                                ("w-2/3", "8/12"),
                                ("w-3/4", "9/12"),
                                ("w-5/6", "10/12"),
                                ("w-11/12", "11/12"),
                                ("w-full", "12/12"),
                            ],
                            "label": "Width SM",
                            "required": False,
                        },
                    ),
                    21: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "_setting": True,
                            "choices": [
                                ("w-1/12", "1/12"),
                                ("w-1/6", "2/12"),
                                ("w-1/4", "3/12"),
                                ("w-1/3", "4/12"),
                                ("w-5/12", "5/12"),
                                ("w-1/2", "6/12"),
                                ("w-7/12", "7/12"),
                                ("w-2/3", "8/12"),
                                ("w-3/4", "9/12"),
                                ("w-5/6", "10/12"),
                                ("w-11/12", "11/12"),
                                ("w-full", "12/12"),
                            ],
                            "label": "Width MD",
                            "required": False,
                        },
                    ),
                    22: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "_setting": True,
                            "choices": [
                                ("w-1/12", "1/12"),
                                ("w-1/6", "2/12"),
                                ("w-1/4", "3/12"),
                                ("w-1/3", "4/12"),
                                ("w-5/12", "5/12"),
                                ("w-1/2", "6/12"),
                                ("w-7/12", "7/12"),
                                ("w-2/3", "8/12"),
                                ("w-3/4", "9/12"),
                                ("w-5/6", "10/12"),
                                ("w-11/12", "11/12"),
                                ("w-full", "12/12"),
                            ],
                            "label": "Width LG",
                            "required": False,
                        },
                    ),
                    23: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "_setting": True,
                            "choices": [
                                ("w-1/12", "1/12"),
                                ("w-1/6", "2/12"),
                                ("w-1/4", "3/12"),
                                ("w-1/3", "4/12"),
                                ("w-5/12", "5/12"),
                                ("w-1/2", "6/12"),
                                ("w-7/12", "7/12"),
                                ("w-2/3", "8/12"),
                                ("w-3/4", "9/12"),
                                ("w-5/6", "10/12"),
                                ("w-11/12", "11/12"),
                                ("w-full", "12/12"),
                            ],
                            "label": "Width XL",
                            "required": False,
                        },
                    ),
                    24: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "_setting": True,
                            "choices": [
                                ("w-1/12", "1/12"),
                                ("w-1/6", "2/12"),
                                ("w-1/4", "3/12"),
                                ("w-1/3", "4/12"),
                                ("w-5/12", "5/12"),
                                ("w-1/2", "6/12"),
                                ("w-7/12", "7/12"),
                                ("w-2/3", "8/12"),
                                ("w-3/4", "9/12"),
                                ("w-5/6", "10/12"),
                                ("w-11/12", "11/12"),
                                ("w-full", "12/12"),
                            ],
                            "label": "Width 2XL",
                            "required": False,
                        },
                    ),
                    25: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("content", 18),
                                ("width", 19),
                                ("width_sm", 20),
                                ("width_md", 21),
                                ("width_lg", 22),
                                ("width_xl", 23),
                                ("width_2xl", 24),
                            ]
                        ],
                        {},
                    ),
                    26: ("wagtail.blocks.ListBlock", (25,), {}),
                    27: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "© ", "label": "Copyright", "required": False},
                    ),
                    28: (
                        "wagtail.blocks.StructBlock",
                        [[("columns", 26), ("copyright_text", 27)]],
                        {},
                    ),
                    29: ("wagtail.blocks.StructBlock", [[("columns", 26)]], {}),
                },
            ),
        ),
        migrations.AlterField(
            model_name="eventeheader",
            name="sections",
            field=wagtail.fields.StreamField(
                [
                    ("top", 8),
                    ("main", 27),
                    ("mobile", 35),
                    ("search_panel", 36),
                    ("cart_panel", 36),
                    ("right_panel", 36),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Top", "label": "Name"},
                    ),
                    1: ("wagtail.blocks.CharBlock", (), {"label": "Text"}),
                    2: ("wagtail.blocks.CharBlock", (), {"label": "Link"}),
                    3: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("flaticon-account", "Account"),
                                ("flaticon-announcement", "Announcement"),
                                ("flaticon-calendar", "Calendar"),
                                ("flaticon-chat-box", "Chat box"),
                                ("flaticon-deal", "Deal"),
                                ("flaticon-fastfood", "Fastfood"),
                                ("flaticon-gps", "GPS"),
                                ("flaticon-handshake", "Handshake"),
                                ("flaticon-mail", "Mail"),
                                ("flaticon-meeting", "Meeting"),
                                ("flaticon-megaphone", "Megaphone"),
                                ("flaticon-phone", "Phone"),
                                ("flaticon-plus", "Plus"),
                                ("flaticon-puzzle", "Puzzle"),
                                ("flaticon-request", "Request"),
                                ("flaticon-search", "Search"),
                                ("flaticon-share", "Share"),
                                ("flaticon-shopping-cart", "Shopping cart"),
                                ("flaticon-speaker", "Speaker"),
                                ("flaticon-surprise", "Surprise"),
                                ("flaticon-teamwork", "Teamwork"),
                                ("flaticon-teamwork-1", "Teamwork 1"),
                                ("flaticon-teamwork-2", "Teamwork 2"),
                                ("flaticon-time", "Time"),
                                ("flaticon-up-right-arrow", "Up right arrow"),
                                ("flaticon-up-right-arrow-1", "Up right arrow 1"),
                            ],
                            "label": "Flaticon",
                            "required": False,
                        },
                    ),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 1), ("link", 2), ("flaticon", 3)]],
                        {},
                    ),
                    5: ("evente.blocks.headers.HeaderSocialMedia", (), {}),
                    6: (
                        "wagtail.blocks.StreamBlock",
                        [[("contact", 4), ("social_media", 5)]],
                        {"label": "Left items", "required": False},
                    ),
                    7: (
                        "wagtail.blocks.StreamBlock",
                        [[("contact", 4), ("social_media", 5)]],
                        {"label": "Right items", "required": False},
                    ),
                    8: (
                        "wagtail.blocks.StructBlock",
                        [[("name", 0), ("left", 6), ("right", 7)]],
                        {"label": "Top header"},
                    ),
                    9: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Main", "label": "Name"},
                    ),
                    10: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {
                            "default": evente.blocks.headers.default_home_page,
                            "label": "Home page",
                        },
                    ),
                    11: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "150px",
                            "help_text": "CSS value, like '150px' or 'auto'",
                            "label": "Width",
                        },
                    ),
                    12: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "auto",
                            "help_text": "CSS value, like '150px' or 'auto'",
                            "label": "Height",
                        },
                    ),
                    13: (
                        "wagtail.blocks.StructBlock",
                        [[("page", 10), ("width", 11), ("height", 12)]],
                        {},
                    ),
                    14: ("evente.blocks.headers.HeaderMainMenu", (), {}),
                    15: ("evente.blocks.headers.HeaderSearch", (), {}),
                    16: ("evente.blocks.headers.HeaderCart", (), {}),
                    17: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Text to display in the button",
                            "required": True,
                        },
                    ),
                    18: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Anchor or link to another website page",
                            "required": False,
                            "validators": [evente.blocks.components.fragment_validator],
                        },
                    ),
                    19: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"help_text": "Link to a page", "required": False},
                    ),
                    20: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "_setting": True,
                            "choices": [("arrow-top-right", "arrow top right")],
                            "icon": "arrow-right-full",
                            "label": "Icon at the end",
                            "required": False,
                        },
                    ),
                    21: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("text", 17),
                                ("url", 18),
                                ("page", 19),
                                ("append_icon", 20),
                            ]
                        ],
                        {},
                    ),
                    22: ("evente.blocks.headers.HeaderMobileButton", (), {}),
                    23: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("logo", 13),
                                ("main_menu", 14),
                                ("search", 15),
                                ("cart", 16),
                                ("call_to_action", 21),
                                ("mobile_button", 22),
                            ]
                        ],
                        {"label": "Left items", "required": False},
                    ),
                    24: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("logo", 13),
                                ("main_menu", 14),
                                ("search", 15),
                                ("cart", 16),
                                ("call_to_action", 21),
                                ("mobile_button", 22),
                            ]
                        ],
                        {"label": "Center items", "required": False},
                    ),
                    25: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("logo", 13),
                                ("main_menu", 14),
                                ("search", 15),
                                ("cart", 16),
                                ("call_to_action", 21),
                                ("mobile_button", 22),
                            ]
                        ],
                        {"label": "Right items", "required": False},
                    ),
                    26: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("logo", 13),
                                ("main_menu", 14),
                                ("search", 15),
                                ("cart", 16),
                                ("call_to_action", 21),
                                ("mobile_button", 22),
                            ]
                        ],
                        {"label": "End items", "required": False},
                    ),
                    27: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("name", 9),
                                ("left", 23),
                                ("center", 24),
                                ("right", 25),
                                ("end", 26),
                            ]
                        ],
                        {"label": "Main header"},
                    ),
                    28: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Mobile", "label": "Name"},
                    ),
                    29: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"label": "Search page"},
                    ),
                    30: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Search here…", "label": "Name"},
                    ),
                    31: (
                        "wagtail.blocks.StructBlock",
                        [[("page", 29), ("text", 30)]],
                        {},
                    ),
                    32: ("evente.blocks.headers.HeaderMobileMainMenu", (), {}),
                    33: ("evente.blocks.headers.HeaderMobileSocialMedia", (), {}),
                    34: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("logo", 13),
                                ("search", 31),
                                ("main_menu", 32),
                                ("call_to_action", 21),
                                ("social_media", 33),
                            ]
                        ],
                        {"label": "Items", "required": False},
                    ),
                    35: (
                        "wagtail.blocks.StructBlock",
                        [[("name", 28), ("items", 34)]],
                        {"label": ""},
                    ),
                    36: ("evente.models.Dummy", (), {"label": ""}),
                },
            ),
        ),
    ]
