# Generated by Django 6.0.4 on 2026-05-04 10:08

import evente.blocks.components
import evente.blocks.headers
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("evente", "0003_alter_eventefooter_content_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventeheader",
            name="sections",
            field=wagtail.fields.StreamField(
                [
                    ("top", 8),
                    ("main", 27),
                    ("mobile", 35),
                    ("search_panel", 36),
                    ("cart_panel", 36),
                    ("right_panel", 36),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Top", "label": "Name"},
                    ),
                    1: ("wagtail.blocks.CharBlock", (), {"label": "Text"}),
                    2: ("wagtail.blocks.CharBlock", (), {"label": "Link"}),
                    3: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("flaticon-account", "Account"),
                                ("flaticon-announcement", "Announcement"),
                                ("flaticon-calendar", "Calendar"),
                                ("flaticon-chat-box", "Chat box"),
                                ("flaticon-deal", "Deal"),
                                ("flaticon-fastfood", "Fastfood"),
                                ("flaticon-gps", "GPS"),
                                ("flaticon-handshake", "Handshake"),
                                ("flaticon-mail", "Mail"),
                                ("flaticon-meeting", "Meeting"),
                                ("flaticon-megaphone", "Megaphone"),
                                ("flaticon-phone", "Phone"),
                                ("flaticon-plus", "Plus"),
                                ("flaticon-puzzle", "Puzzle"),
                                ("flaticon-request", "Request"),
                                ("flaticon-search", "Search"),
                                ("flaticon-share", "Share"),
                                ("flaticon-shopping-cart", "Shopping cart"),
                                ("flaticon-speaker", "Speaker"),
                                ("flaticon-surprise", "Surprise"),
                                ("flaticon-teamwork", "Teamwork"),
                                ("flaticon-teamwork-1", "Teamwork 1"),
                                ("flaticon-teamwork-2", "Teamwork 2"),
                                ("flaticon-time", "Time"),
                                ("flaticon-up-right-arrow", "Up right arrow"),
                                ("flaticon-up-right-arrow-1", "Up right arrow 1"),
                            ],
                            "label": "Flaticon",
                            "required": False,
                        },
                    ),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 1), ("link", 2), ("flaticon", 3)]],
                        {},
                    ),
                    5: ("evente.blocks.headers.HeaderSocialMedia", (), {}),
                    6: (
                        "wagtail.blocks.StreamBlock",
                        [[("contact", 4), ("social_media", 5)]],
                        {"label": "Left items", "required": False},
                    ),
                    7: (
                        "wagtail.blocks.StreamBlock",
                        [[("contact", 4), ("social_media", 5)]],
                        {"label": "Right items", "required": False},
                    ),
                    8: (
                        "wagtail.blocks.StructBlock",
                        [[("name", 0), ("left", 6), ("right", 7)]],
                        {"label": "Top header"},
                    ),
                    9: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Main", "label": "Name"},
                    ),
                    10: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {
                            "default": evente.blocks.headers.default_home_page,
                            "label": "Home page",
                        },
                    ),
                    11: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "150px",
                            "help_text": "CSS value, like '150px' or 'auto'",
                            "label": "Width",
                        },
                    ),
                    12: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "auto",
                            "help_text": "CSS value, like '150px' or 'auto'",
                            "label": "Height",
                        },
                    ),
                    13: (
                        "wagtail.blocks.StructBlock",
                        [[("page", 10), ("width", 11), ("height", 12)]],
                        {},
                    ),
                    14: ("evente.blocks.headers.HeaderMainMenu", (), {}),
                    15: ("evente.blocks.headers.HeaderSearch", (), {}),
                    16: ("evente.blocks.headers.HeaderCart", (), {}),
                    17: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Anchor or link to another website page",
                            "required": False,
                            "validators": [evente.blocks.components.fragment_validator],
                        },
                    ),
                    18: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"help_text": "Link to a page", "required": False},
                    ),
                    19: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Text to display in the button",
                            "required": True,
                        },
                    ),
                    20: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "_setting": True,
                            "choices": [("arrow-top-right", "Arrow top right")],
                            "icon": "arrow-right-full",
                            "label": "Icon at the end",
                            "required": False,
                        },
                    ),
                    21: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("url", 17),
                                ("page", 18),
                                ("text", 19),
                                ("append_icon", 20),
                            ]
                        ],
                        {},
                    ),
                    22: ("evente.blocks.headers.HeaderMobileButton", (), {}),
                    23: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("logo", 13),
                                ("main_menu", 14),
                                ("search", 15),
                                ("cart", 16),
                                ("call_to_action", 21),
                                ("mobile_button", 22),
                            ]
                        ],
                        {"label": "Left items", "required": False},
                    ),
                    24: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("logo", 13),
                                ("main_menu", 14),
                                ("search", 15),
                                ("cart", 16),
                                ("call_to_action", 21),
                                ("mobile_button", 22),
                            ]
                        ],
                        {"label": "Center items", "required": False},
                    ),
                    25: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("logo", 13),
                                ("main_menu", 14),
                                ("search", 15),
                                ("cart", 16),
                                ("call_to_action", 21),
                                ("mobile_button", 22),
                            ]
                        ],
                        {"label": "Right items", "required": False},
                    ),
                    26: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("logo", 13),
                                ("main_menu", 14),
                                ("search", 15),
                                ("cart", 16),
                                ("call_to_action", 21),
                                ("mobile_button", 22),
                            ]
                        ],
                        {"label": "End items", "required": False},
                    ),
                    27: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("name", 9),
                                ("left", 23),
                                ("center", 24),
                                ("right", 25),
                                ("end", 26),
                            ]
                        ],
                        {"label": "Main header"},
                    ),
                    28: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Mobile", "label": "Name"},
                    ),
                    29: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"label": "Search page"},
                    ),
                    30: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "Search here…", "label": "Name"},
                    ),
                    31: (
                        "wagtail.blocks.StructBlock",
                        [[("page", 29), ("text", 30)]],
                        {},
                    ),
                    32: ("evente.blocks.headers.HeaderMobileMainMenu", (), {}),
                    33: ("evente.blocks.headers.HeaderMobileSocialMedia", (), {}),
                    34: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("logo", 13),
                                ("search", 31),
                                ("main_menu", 32),
                                ("call_to_action", 21),
                                ("social_media", 33),
                            ]
                        ],
                        {"label": "Items", "required": False},
                    ),
                    35: (
                        "wagtail.blocks.StructBlock",
                        [[("name", 28), ("items", 34)]],
                        {"label": ""},
                    ),
                    36: ("evente.models.Dummy", (), {"label": ""}),
                },
            ),
        ),
        migrations.AlterField(
            model_name="eventesettings",
            name="social_media",
            field=wagtail.fields.StreamField(
                [("link", 4)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "", "label": "Name"},
                    ),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "#",
                            "label": "Link",
                            "validators": [evente.blocks.components.fragment_validator],
                        },
                    ),
                    2: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("fa-regular", "Regular"),
                                ("fa-light", "Light"),
                                ("fa-brands", "Brands"),
                                ("fa-solid", "Solid"),
                            ],
                            "label": "Font Awesome style",
                        },
                    ),
                    3: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "fa-globe",
                            "help_text": "https://fontawesome.com/v6/search?ic=free-collection",
                            "label": "Font Awesome name",
                        },
                    ),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("href", 1), ("fa_style", 2), ("fa_name", 3)]],
                        {},
                    ),
                },
            ),
        ),
    ]
